# This is a Template for a course of the Open Courses project
# It is written in TOML. You can check the sintax at github.com/toml-lang/toml

#####################################
#        MANDATORY FIELDS           #
#####################################

# We will periodically update the course template and the version will be used
# by the parser to see which fields are available and grant back compatibility
version = 1.0

# Title and subtitle of the Course
title = "Example Course"
subtitle = "An example on how to create a course"

# Each course can have one or more mantainers
[maintainers]
Antonio Langiu
Lorenzo Moro

# Each course can have one or more contributors
[contributors]
Roberta Bardini

# The GitHub url where the course is pubblished
url = https://github.com/opencourses/open_courses_scripts

# The description of the course (you can write in MarkDown)
description = '''
This course explains how to **create** and **manage** an
Open Course repository. This text will be then used to generate
the README.md inserted in each repository but also to create the
course description in the static page of the course.
'''

#####################################
#          OPTIONAL FIELDS          #
#####################################

# This field defines the folder where the exercises are inserted
exercise_dir = "exercise"

# The name used to define an exercise (for example: exercise01)
exercise_prefix = "exercise"
